yml check

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -29,7 +29,10 @@ jobs:
         ./lab4 trace 1,2-4,3 100 3 \
           P1,0,5 P2,2,3 P3,4,2
 
-    - name: Verify build artifacts
+    - name: Test the build artifacts
       run: |
         # Verify that the executable exists and is executable
-        if [ ! -x ./cpu-scheduler ]; then echo "Executable not found" && exit 1; fi
+        if [ ! -x ./lab4 ]; then
+          echo "Executable not found or not executable"
+          exit 1
+        fi
